# This continuous integration pipeline is triggered anytime a user pushes code to the repo.
name:  Eve-Squadron Continious Integration

# Trigger on every master branch push and pull request
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    # Publish EveSquadron-Linux (x64)
    - name: Publish EveSquadron-Linux (x64)
      run:  |
        $tag=$(git describe --tags --abbrev=0)
        dotnet publish "./EveSquadron/EveSquadron.csproj" -c Release -o ./EveSquadron-Linux -r linux-x64 -p:Version="$tag"

    # Publish EveSquadron-Windows (x64)
    - name: Publish EveSquadron-Windows (x64)
      run: |
        $tag=$(git describe --tags --abbrev=0)
        dotnet publish "./EveSquadron/EveSquadron.csproj" -c Release -o ./EveSquadron-Windows -r win-x64 -p:OutputType="WinExe" -p:Version="$tag"

    # Publish EveSquadron-MacOS (x64)
    - name: Publish EveSquadron-MacOS (x64)
      run:  |
        $tag=$(git describe --tags --abbrev=0)
        dotnet publish "./EveSquadron/EveSquadron.csproj" -c Release -o ./EveSquadron-MacOS -r osx-x64 -p:Version="$tag"

    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v3
      with:
        name: EveSquadron-Linux
        path: EveSquadron-Linux
          
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v3
      with:
        name: EveSquadron-Windows
        path: EveSquadron-Windows
        
    - name: Upload MacOS artifacts
      uses: actions/upload-artifact@v3
      with:
        name: EveSquadron-MacOS
        path: EveSquadron-MacOS
