# This continuous integration pipeline is triggered anytime a user pushes code to the repo.
name:  EVEye Continious Integration

# Trigger on every master branch push and pull request
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    # Publish EVEye-Linux (x64)
    - name: Publish EVEye-Linux (x64)
      run:  dotnet publish -c Release -o ./EVEye-Linux -r linux-x64 --self-contained true --p:PublishSingleFile=true 

    # Publish EVEye-Windows (x64)
    - name: Publish EVEye-Linux (x64)
      run:  dotnet publish -c Release -o ./EVEye-Windows -r win-x64 --self-contained true --p:PublishSingleFile=true 

    # Publish EVEye-MacOS (x64)
    - name: Publish EVEye-MacOS (x64)
      run:  dotnet publish -c Release -o ./EVEye-MacOS -r osx-x64 --self-contained true --p:PublishSingleFile=true 

    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v3
      with:
        name: EVEye-Linux
        path: EVEye-Linux
          
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v3
      with:
        name: EVEye-Windows
        path: EVEye-Windows
        
    - name: Upload MacOS artifacts
      uses: actions/upload-artifact@v3
      with:
        name: EVEye-Linux
        path: EVEye-MacOS
